# NOTE: update this with your service name
service: search-place

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}


provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  environment:
    ggKey: ${self:custom.environment.ggKey}
    yelpKey: ${self:custom.environment.yelpKey}

functions:
  search:
    handler: search.main
    events:
      - http:
          path: search
          method: get
          cors: true

  nextpage:
    handler: next-page.main
    events:
      - http:
          path: nextpage
          method: get
          cors: true

  yelpreview:
    handler: yelp-review.main
    events:
      - http:
          path: yelpreview
          method: get
          cors: true


