# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'searchPlace' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for searchPlace
  pod "McPicker"
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod "EasyToast"
  pod "SwiftSpinner"
  pod "Cosmos"
  pod "Alamofire"
  pod 'Kingfisher', '~> 4.0'
  pod 'FontAwesome.swift'

  target 'searchPlaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'searchPlaceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
