application: v1-csci517-hw8
version: 448888
runtime: php55
api_version: 1
threadsafe: true


handlers:

-   url: /css  #your css folder
    static_dir: css

-   url: /scripts #your javascript folder
    static_dir: scripts


-   url: /index.php
    script: index.php

-   url: .*
    script: index.html